# Sets up local environment so that CUDA can be found by Relion

---
- name: Find Cuda absolute path
  shell: readlink -f `which nvcc`
  environment: 
    PATH: "{{ find_cuda_path }}"
    LD_LIBRARY_PATH: "{{ find_cuda_lib }}"
  register: which_nvcc

- name: Symlink cuda install dir to /usr/local/cuda
  file: 
    src: "{{ which_nvcc.stdout|replace('/bin/nvcc','') }}"
    dest: "{{ cuda_symlink }}"
    state: link
  become: yes

- name: Set up local profile to include CUDA environment variables 
  template:
    src: "cuda.sh.j2"
    dest: "{{ profile_dir }}cuda.sh"
  become: yes