# Sets up local environment so that CUDA can be found by Relion

---
- name: Symlink cuda install dir to /usr/local/cuda
  file: 
    src: "{{ cuda_install_dir }}"
    dest: "{{ cuda_symlink }}"
    state: link
  become: yes

- name: Set up local profile to include CUDA environment variables 
  template:
    src: "cuda.sh.j2"
    dest: "{{ profile_dir }}cuda.sh"
  become: yes