---

# Base installation of RELION 2.0, without any auxillary software (e.g. motion correction, ctf estimation, etc.)

- name: Relion - remove previous build directories
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "{{ relion_build_dir }}"
    - "{{ relion_download_dir }}external/"

- name: Relion - create a new build directory
  file: 
    state: directory
    path: "{{relion_build_dir }}"


- debug:
    msg: "About to configure Relion. Configuration output and error messages will be written to: {{relion_build_dir}}cmake.out and cmake.err"

- name: Relion - configure build
  # options:
  # double precision on/off -DDoublePrec_GPU=ON
  # set computer version of CUDA-capable device (i.e. GPU) -DCUDA_ARCH=61
  # system-wide install location -DCMAKE_INSTALL_PREFIX={{ relion_ver_dir }}
  shell: cmake -DCUDA_ARCH={{ cuda_arch }} -DCMAKE_INSTALL_PREFIX={{relion_ver_dir}} .. > cmake.out 2> cmake.err
  args:
    chdir: "{{relion_build_dir }}"


- debug:
    msg: "About to build Relion. Build output and error messages will be written to: {{relion_build_dir}}make.out and make.err"

- name: Relion - make build 
  shell: make -j {{ threads }} > make.out 2> make.err
  args:
    chdir: "{{relion_build_dir }}"


- name: Relion - install
  shell: make install > install.out 2> install.err
  args:
    chdir: "{{relion_build_dir }}"
