---

# Base installation of RELION 2.0, without any auxillary software (e.g. motion correction, ctf estimation, etc.)

- name: Relion - create a new build directory
# if build directory exists; remove it
  file:
    state: absent
    path: "{{relion_build_dir }}"
  file: 
    state: directory
    path: "{{relion_build_dir }}"


- debug:
    msg: "About to configure Relion. Configuration output and error messages will be written to: {{relion_build_dir}}cmake.out and cmake.err"

- name: Relion - configure build
  # options:
  # double precision on/off -DDoublePrec_GPU=ON
  # set computer version of CUDA-capable device (i.e. GPU) -DCUDA_ARCH=61
  # system-wide install location -DCMAKE_INSTALL_PREFIX={{ relion_ver_dir }}
  # use the FFTW and FLTK libraries packaged with Relion, instead of local versions
  shell: cmake -DCUDA_ARCH={{ cuda_arch }} -DFORCE_OWN_FFTW=ON -DFORCE_OWN_FLTK=ON -DCMAKE_INSTALL_PREFIX={{relion_ver_dir}} .. > cmake.out 2> cmake.err
  args:
    chdir: "{{relion_build_dir }}"


- debug:
    msg: "About to build Relion. Build output and error messages will be written to: {{relion_build_dir}}make.out and make.err"

- name: Relion - make build 
  shell: make > make.out 2> make.err
  args:
    chdir: "{{relion_build_dir }}"


- name: Relion - install
  shell: make install > make_install.out 2> make_install.err
  args:
    chdir: "{{relion_build_dir }}"
