---
# Install auxiliary software that Relion uses -- e.g. for motion correction, ctf estimation, local resolution estimation, etc.



#    - name: MotionCorr - download and untar
#      get_url:
#        url: "{{motioncorr_dl_link }}"
#        dest: "{{ motioncorr_install_dir  }}"

#     unarchive:
#       src:  "{{motioncorr_dl_link }}"
#       dest: "{{install_dir }}"
#       remote_src: yes
#       creates: "{{motioncorr_exe_path}}"

#  - name: MotionCorr - make build 
#    command: make
#    args:
#        chdir: "{{ motioncorr_src_dir }}"

- name: unblur - download and untar
  unarchive:
    src: "{{unblur_dl_link }}"
    dest: "{{unblur_install_dir}}"
    remote_src: yes
    creates: "{{unblur_exe_path}}"

- name: summovie - download and untar
  unarchive:
    src: "{{summovie_dl_link }}"
    dest: "{{summovie_install_dir}}"
    remote_src: yes
    creates: "{{summovie_exe_path}}"

- name: CTFFIND4 - download and untar
  unarchive:
    src: "{{ctffind4_dl_link }}"
    dest: "{{ctffind4_install_dir}}"
    remote_src: yes
    creates: "{{ctffind4_exe_path}}"

- name: GCTF - download and untar   
  unarchive:
    src: "{{gctf_dl_link }}"
    dest: "{{gctf_install_dir}}"
    remote_src: yes
    creates: "{{gctf_exe_path}}"

- name: RESMAP - download
  get_url:
    url: "{{resmap_dl_link }}"
    dest: "{{resmap_exe_path}}"
    mode: 0755