---
# Install auxiliary software that Relion uses -- e.g. for motion correction, ctf estimation, local resolution estimation, etc.
# For any given software, download and installation will be skipped if there is already an executable at the expected path (see var file)
# To download a new version, change the version number in the var file.

- name: Check if MotionCorr installed
  stat:
    path: "{{motioncorr_exe_path}}"
  register: motioncorr_path

- name: Install MotionCorr
  when: not motioncorr_path.stat.exists
  include: install_motioncorr.yaml



- name: Check if Unblur installed
  find:
    paths: "{{ unblur_ver_dir }}bin"
    pattern: "*.exe"
  register: unblur_find

- name: unblur - download and untar executable
  when: "{{ int(unblur_find.matched) > 0 }}"
  unarchive:
    src: "{{unblur_dl_link }}"
    dest: "{{unblur_install_dir}}"
    remote_src: yes


- name: Check if Summovie installed
  find:
    paths: "{{ summovie_ver_dir }}bin"
    pattern: "*.exe"
  register: summovie_find

- name: summovie - download and untar executable
  when: "{{ int(summovie_find.matched) > 0 }}"
  unarchive:
    src: "{{summovie_dl_link }}"
    dest: "{{summovie_install_dir}}"
    remote_src: yes




- name: CTFFIND4 - download and untar executable
  unarchive:
    src: "{{ ctffind4_dl_link }}"
    dest: "{{ ctffind4_ver_dir }}"
    remote_src: yes
    creates: "{{ctffind4_exe_path}}"





- name: GCTF - download and untar executables
  unarchive:
    src: "{{gctf_dl_link }}"
    dest: "{{gctf_install_dir}}"
    remote_src: yes




- name: RESMAP - download executable
  get_url:
    url: "{{ resmap_dl_link }}"
    dest: "{{ resmap_exe_path }}"
    mode: 0755
    validate_certs: False