- name: Create individual software directories
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{relion_download_dir}}"
    - "{{relion_ver_dir}}"
    - "{{motioncorr_ver_dir}}"
    - "{{motioncor2_install_dir}}"
    - "{{unblur_ver_dir}}"
    - "{{summovie_ver_dir}}"
    - "{{ctffind4_ver_dir}}"
    - "{{gctf_install_dir}}"
    - "{{resmap_install_dir}}"




- name: Relion - clone or pull from git repository
  git: 
    repo: "{{ relion_repo }}"
    version: "{{ relion_repo_branch }}"
    dest: "{{ relion_download_dir }}"
  register: relion_git



- name: Check if Relion 2.0 is already installed
  stat:
    path: "{{relion_exe_path}}"
  register: relion_exe_stat


- name: Display message
  when: relion_exe_stat.stat.exists and {{ relion_git.before == relion_git.after }}
  debug:
    msg: "Relion 2.0 seems to already be installed, with an executable at {{relion_exe_path}} If you want to re-do the installation, please delete the existing installation folder {{ relion_ver_dir }} first. If you are a developer and want to install another version of Relion 2.0 in a different location, please change the variable 'relion_ver_dir' in the variables file 'group_vars/all'. The playbook will now continue with the existing Relion 2.0 installation."


# Install Relion 2.0 if
# 1) there is no relion executable found in the install path 
# 2) if the repository has been updated
- name: Install Relion 2.0
  when: not relion_exe_stat.stat.exists or {{ relion_git.before != relion_git.after }}
  include: install_relion_base.yaml
  environment:
    PATH: "{{ansible_env.PATH}}:{{ local_bin }}"
    LD_LIBRARY_PATH: "{{ local_lib }}"




- name: Relion - check for custom Python scripts
  stat:
    path: "{{ relion_download_dir }}python/"
  register: relion_dl_python_check

- name: Relion - copy custom Python scripts to installation directory
  synchronize:
    src: "{{ relion_download_dir }}python/"
    dest: "{{ relion_python_dir }}"
    recursive: yes
    delete: yes
  when: relion_dl_python_check.stat.exists




#- name: Relion - add default mpirun hosts file to installation directory
#  include: hostfiles.yaml





- name: Install auxiliary software if not already installed
  include: install_aux.yaml


