---

# Install Git Large File Storage to local machine

- set_fact:
    gitlfs_link: "https://github.com/git-lfs/git-lfs/releases/download/v1.5.5/git-lfs-linux-amd64-1.5.5.tar.gz"
    


- name: Git Large File Storage - download and untar
  unarchive:
    src: "{{ gitlfs_link }}"
    dest: "{{ download_dir }}"
    remote_src: yes

- name: Git LFS - install 
  shell: "./install.sh"
  args:
    chdir: "{{ download_dir }}git-lfs-1.5.5/"
  become: yes    

- name: Git LFS - check installation
  shell: "git lfs install"