---
- name: Install LMOD dependencies
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - liblua5.2-0
    - liblua5.2-dev
    - lua5.2
    - lua-filesystem-dev
    - lua-posix
  become: yes
