---

# install OpenMPI packages

- name: Install OpenMPI
  apt: 
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - openmpi-bin
    - openmpi-common
    - openssh-client
    - openssh-server
    - libopenmpi-dev