---
- hosts: drivers
  become: yes
  tasks:
    - name: Add graphics driver apt repository
      apt_repository: repo="ppa:graphics-drivers/ppa"

    - name: Install build tools and refresh apt package list
      apt: name={{ item }} state=present update_cache=yes
      with_items:
        - build-essential
        - dkms
        - freeglut3-dev
        - libglu1-mesa-dev

    - name: Install drivers
      apt: name={{ driver_pkg }} state=present

    - name: Set up cuda environment
      file: path={{ cuda_env_script }} state=touch
    - lineinfile: dest={{ cuda_env_script }} line="export PATH=$PATH:/usr/local/cuda/bin"
    - lineinfile: dest={{ cuda_env_script }} line="export CUDADIR=/usr/local/cuda"
    - lineinfile: dest={{ cuda_env_script }} line="export GLPATH=/usr/lib"

- hosts: installer
  become: yes
  tasks:
    
    - name: Check if CUDA directory exists
      stat: path=/usr/local/cuda
      register: p
      
    - name: Download cuda if it doesn't exist
      get_url: url={{ cuda_dl }} dest=/tmp/installer.run mode=0755
      when: not p.stat.exists
      
    - name: Run the installer command
      command: /tmp/installer.run --silent --toolkit --samples --samplespath={{ cuda_install_dir }}/samples --toolkitpath={{ cuda_install_dir }} --override
      when: not p.stat.exists
      
    - name: Symlink cuda install dir to /usr/local/cuda
      file: src={{ cuda_install_dir }} dest={{ cuda_install_link }} state=link
      when: not p.stat.exists
