- name: Determine number of available GPUs
  shell: nvidia-smi --query-gpu=name --format=csv,noheader | wc -l 
  register: num_gpu

- name: Create default GPU hostfile
  template:
    src: "gpu.hosts.j2"
    dest: "{{ relion_default_hostfile }}"
  run_once: True 


- name: Determine number of available CPUs
  shell: grep -c ^processor /proc/cpuinfo
  register: num_cpu

- name: Create default CPU hostfile
  template:
    src: "cpu.hosts.j2"
    dest: "{{ relion_default_hostfile_cpu }}"
  run_once: True 
