---
- name: Try to find CUDA 8.0
  shell: "nvcc --version | grep '8.0'"
  register: nvcc_80
  environment:
    PATH: "{{ansible_env.PATH}}:{{cuda_bin}}"
    LD_LIBRARY_PATH: "{{cuda_lib}}"
  ignore_errors: true # do not stop playbook if CUDA not found


# if cuda found
- debug:
    msg: "CUDA 8.0 found. Skipping installation of CUDA 8.0 Toolkit."
  when: nvcc_80|succeeded



# if cuda not found
- pause:
    prompt: "CUDA 8.0 was not found when checking with command 'nvcc --version', using location {{cuda_install_dir}} found in playbook inventory file. Playbook will attempt installation of CUDA 8.0 Toolkit. Press 'enter' to continue. Press 'ctrl+c' and then 'a' to abort."
  when: nvcc_80|failed

- name: Install CUDA
  include: cuda.yaml
  when: nvcc_80|failed 



