# Set up environment variables and links on all machines for running IMOD.
---
- name: Setup local IMOD environment variables for each machine.
  copy:
    dest: /etc/profile.d/IMOD-linux.sh
    src: "{{ imod_install_dir }}IMOD/IMOD-linux.sh"
    follow: yes