# Install TensorFlow and related libraries with GPU support.

---
- name: Install cuDNN library
  unarchive:
    src: "{{ cudnn_link }}"  
    dest: "{{ cuda_lib_path }}"
    remote_src: True

- name: Uninstall any existing protobuf package via pip
  pip:
    name: protobuf
    executable: "{{ python_bin }}/pip"
    state: absent
  environment:
    PATH: "{{ python_bin }}:{{ ansible_env.PATH }}"

- name: Install TensorFlow for GPU via pip
  pip:
    name: tensorflow-gpu
    executable: "{{ python_bin }}/pip"
    state: present
    version: "{{ tensorflow_ver }}"
  environment:
    PATH: "{{ python_bin }}:{{ ansible_env.PATH }}"
