---
# Install dependencies for TensorFlow on each machine.

- name: Install libcupti-dev library
  apt:
    name: libcupti-dev
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  become: yes