# Set up environment variables and links for running Relion.
---
- name: Setup local Relion environment variables for each machine.
  blockinfile:
    dest: /etc/profile.d/relion.sh
    create: yes
    block: |
      #!/bin/sh


      # Set up environment variables for RELION-2.0
      export PATH=$PATH:{{relion_bin}}
      export LD_LIBRARY_PATH={{relion_lib}}:$LD_LIBRARY_PATH


      # Set up Relion-specific environment variable for CUDA
      export CUDA_HOME=/usr/local/cuda



      # Default PDF viewer
      export RELION_PDFVIEWER_EXECUTABLE=evince

      # Default MOTIONCORR executable
      export RELION_MOTIONCORR_EXECUTABLE={{motioncorr_exe_path}}

      # Default UNBLUR/SUMMOVIE executables
      export RELION_UNBLUR_EXECUTABLE={{unblur_exe_path}}
      export RELION_SUMMOVIE_EXECUTABLE={{summovie_exe_path}}

      # Default CTFFIND executable, version 4.1
      export RELION_CTFFIND_EXECUTABLE={{ctffind4_exe_path}}

      # Default Gctf executable
      export RELION_GCTF_EXECUTABLE={{gctf_exe_path}}

      # Default ResMap executable
      export RELION_RESMAP_EXECUTABLE={{resmap_exe_path}}

      # Enforce cluster jobs to occupy entire nodes with 24 hyperthreads
      #export RELION_MINIMUM_DEDICATED 24

      # Do not allow the user to change the enforcement of entire nodes
      #export RELION_ALLOW_CHANGE_MINIMUM_DEDICATED 0

      # Ask for confirmation if users try to submit local jobs with more than 12 MPI nodes
      #export RELION_WARNING_LOCAL_MPI 12


- name: Link libtiff library for MotionCor2
  file:
    state: link
    path: /usr/lib/libtiff.so.3
    src:  /usr/lib/x86_64-linux-gnu/libtiff.so.5
    follow: yes
  become: yes