- name: Install client
  apt: name=beegfs-client state=present
  
- name: Configure the client and create mount point
  file: path={{ mount_point }} state=directory
- lineinfile: dest=/etc/beegfs/beegfs-client.conf regexp='^sysMgmtdHost' line='sysMgmtdHost = {{ mgmt_host }}'
- copy: dest=/etc/beegfs/beegfs-mounts.conf content='{{ mount_point }} /etc/beegfs/beegfs-client.conf'
- lineinfile: dest=/etc/beegfs/beegfs-client.conf regexp='^connInterfacesFile' line='connInterfacesFile = /etc/beegfs/interface'
- lineinfile: dest=/etc/beegfs/interface line='{{ network_interface }}' create=yes

- name: Create the scratch filesystem
  filesystem:
    fstype: ext4
    dev: /dev/{{ scratch_device }}
    opts: -i 2048 -I 1024 -J size=400 -Odir_index,filetype -L scratch

- name: Mount the scratch drive
  file: path={{ scratch_dir }} state=directory
- mount:
    src: /dev/{{ scratch_device }}
    name: "{{ scratch_dir }}"
    state: mounted
    fstype: ext4
    opts: noatime,nodiratime

- name: Start the helper service and build the client kernel module
  command: "service beegfs-client rebuild"

- service: name=beegfs-helperd state=restarted
- service: name=beegfs-client state=restarted

