---
- name: Add the new user and create ssh keys
  user:
    name: "{{ user }}"
    password: "{{ password }}"
    generate_ssh_key: yes
    ssh_key_bits: "{{ key_size }}"
    ssh_key_file: .ssh/id_rsa
    shell: /bin/bash

- name: Get SSH public key of the new user
  shell: cat /home/{{ user }}/.ssh/id_rsa.pub
  register: ssh_key
  
- name: Deploy public key of new user across all nodes
  authorized_key: 
    user: "{{ user }}"
    key: "{{ ssh_key.stdout }}"
  delegate_to: "{{ item }}"
  with_items:
    - "{{ groups['add_user'] }}" 

- debug:
    msg: "Public keys deployed. User is now authorized to SSH as themselves into other nodes without password prompt."
    run_once: true




- name: Add new user as known host across all nodes
  known_hosts:
    path: "/home/{{ user }}/.ssh/known_hosts"
    name: "{{ inventory_hostname }}"
    key: "{{ inventory_hostname }} {{ ssh_key.stdout }}"
  delegate_to: "{{ item }}"
  with_items:
   - "{{ groups['add_user'] }}"






- name: Get name of current sudo user running Ansible
  local_action: command whoami
  register: local_user
  become: no

- name: Get sudo user's SSH key
  shell: cat /home/{{ local_user.stdout }}/.ssh/id_rsa.pub
  register: ssh_key_local

- name: Deploy public key of sudo user to new user on all nodes
  authorized_key:
    user: "{{ user }}"
    key: "{{ ssh_key_local.stdout }}"
  delegate_to: "{{ item }}"
  with_items:
    - "{{ groups['add_user'] }}"

- debug:
    msg: "Public key of sudo user deployed. Sudo user can SSH into new user without password prompt."
    run_once: true 