---
- hosts: localhost
  become: yes
  roles:
    - depends


- hosts: add_user
  become: yes
  vars_prompt:
    - name: user
      prompt: "create username"
      private: no
    - name: password
      prompt: "create password"
      private: yes
      encrypt: sha512_crypt
      confirm: yes
      salt_size: 7
  roles:
    - add_user
    - relion_ready