---
- name: Install OpenMPI and run dependencies on all machines
  hosts: machines
  become: yes
  roles:
    - updated_apt_cache
    - openmpi
    - run_depends

- name: Install Relion and auxiliary software on shared drive
  hosts: installer
  roles:
    - build_depends
    - shared_relion

- name: Install IMOD
  hosts: installer
  roles:
    - shared_imod

# set up the environment variables for all machines
- name: Set up the environment variables for all machines
  hosts: machines
  become: yes
  roles:
    - relion_env
    - imod_env