---
- name: Install OpenMPI and run dependencies on all machines
  hosts: machines
  become: yes
  roles:
    - updated_apt_cache
    - openmpi
    - run_depends

- name: Install dependencies for building and installation of other software
  hosts: installer
  become: yes
  roles:
    - build_depends


- name: Install Relion and auxiliary software on shared drive
  hosts: installer
  roles:
    - shared_relion

- name: Install IMOD
  hosts: installer
  roles:
    - shared_imod

- name: Install Anaconda
  hosts: installer
  roles:
    - shared_python

# set up the environment variables for all machines
- name: Set up the environment variables for all machines
  hosts: machines
  become: yes
  roles:
    - relion_env
    - imod_env
    - python_env