---
# install OpenMPI on all machines
- hosts: all
  become: yes
  roles:
    - openmpi

# install Relion and associated software on a shared drive using the local host.
- hosts: localhost
  become: yes
  roles:
    - shared_install

# set up the environment variables for all machines
- hosts: all
  become: yes
  roles:
    - environment