---
- name: Install OpenMPI and build dependencies on all machines
  hosts: machines
  become: yes
  roles:
    - updated_apt_cache
    - openmpi
    - build_depends

- name: Install Relion and auxiliary software on shared drive
  hosts: installer
  become: yes
  roles:
    - shared_relion

# set up the environment variables for all machines
- name: Set up the environment variables for all machines
  hosts: machines
  become: yes
  roles:
    - relion_env