---
- name: Install OpenMPI and run dependencies on all machines
  hosts: machines
  roles:
    - openmpi
    - run_depends

- name: Install dependencies for building and installation of other software
  hosts: installer
  roles:
    - build_depends


- name: Install Anaconda
  hosts: installer
  roles:
    - shared_python

- include: tensorflow.yaml

- name: Install Relion and auxiliary software on shared drive
  hosts: installer
  roles:
    - shared_relion
    

- name: Install IMOD
  hosts: installer
  roles:
    - shared_imod
    
#- name: Install Lmod
#  hosts: installer
#  roles:
#    - shared_lmod


# set up the environment variables for all machines
- name: Set up the environment variables for all machines
  hosts: machines
  roles:
    - relion_hostfile
    - relion_env
    - imod_env
    - python_env


- name: Sanity check
  hosts: installer
  roles:
    - relion_sane
