---
- name: Install OpenMPI and run dependencies on all machines
  hosts: machines
  roles:
    - openmpi
    - run_depends

- name: Install dependencies for building and installation of other software
  hosts: installer
  roles:
    - build_depends


- name: Install Anaconda
  hosts: installer
  roles:
    - shared_python

- include: tensorflow.yaml

- name: Install Relion and auxiliary software on shared drive
  hosts: installer
  roles:
    - shared_relion
    

- name: Install IMOD
  hosts: installer
  roles:
    - shared_imod
    
# Don't install LMOD in this playbook, we have a separate playbook for it    
#- name: Install Lmod
#  hosts: installer
#  roles:
#    - shared_lmod


# TODO: Replace this with SLURM
- name: Set up relion hostfile
  hosts: machines
  roles:
    - relion_hostfile

# set up the environment variables for all machines
# we used to do this with profile.d scripts, but now we use LMOD
# - name: Set up the environment variables for all machines
#   hosts: machines
#   roles:
#     - relion_hostfile
#     - relion_env
#     - imod_env
#     - python_env
- name: Set up modulefile for this version of RELION
  hosts: machines
  roles:
    - shared_module

- name: Sanity check
  hosts: installer
  roles:
    - relion_sane
