---
# install OpenMPI on all machines
- hosts: all
  become: yes
  roles:
    - openmpi
    - build_depends

# install Relion and associated software on a shared drive using the local host.
- hosts: installer
  become: yes
  roles:
    - shared_relion

# set up the environment variables for all machines
- hosts: all
  become: yes
  roles:
    - relion_env