---
- name: Install TensorFlow dependencies
  hosts: machines
  roles:
    - tensorflow_depends

- name: Install TensorFlow
  hosts: installer
  roles:
    - shared_tensorflow
  environment:
    PATH: "{{ anaconda_bin }}:{{ ansible_env.PATH }}"